#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "$PROJECT_ROOT"

log() { echo >&2 "[add-s3] $*"; }
die() { echo >&2 "[add-s3] ERROR: $*"; exit 1; }

dc() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  elif command -v docker-compose >/dev/null 2>&1; then
    docker-compose "$@"
  else
    die "Neither 'docker compose' nor 'docker-compose' is available."
  fi
}

if [ ! -f ".env" ]; then
  die ".env not found. Run: ./scripts/init-odk.sh"
fi

backup_env() {
  local ts
  ts="$(date +%Y%m%d-%H%M%S)"
  local backup=".env.backup.${ts}"
  cp .env "$backup"
  log "Backed up existing .env to ${backup}"
}

backup_env

set +u
source .env
set -u

if [ "${VG_GARAGE_ENABLED:-false}" != "true" ]; then
  die "VG_GARAGE_ENABLED is not true in .env. Re-run init and choose Garage."
fi

if [ ! -f "docker-compose-garage.yml" ]; then
  die "docker-compose-garage.yml not found. Re-run: ./scripts/init-odk.sh"
fi

compose_files=(-f docker-compose.yml -f docker-compose-garage.yml)

log "Starting Garage..."
dc "${compose_files[@]}" up -d garage

if ! docker ps --format '{{.Names}}' | grep -q '^odk-garage$'; then
  die "Garage container not running (expected name: odk-garage)."
fi

garage() {
  docker exec odk-garage /garage "$@"
}

log "Waiting for Garage to respond..."
for i in $(seq 1 60); do
  if garage status >/dev/null 2>&1; then
    break
  fi
  sleep 1
  if [ "$i" -eq 60 ]; then
    die "Garage did not become ready. Check: docker logs odk-garage | tail -50"
  fi
done

capacity="10G"
if [ -f "garage/storage.conf" ]; then
  capacity="$(tr -d ' \t\r\n' < garage/storage.conf)"
fi
if [ -z "$capacity" ]; then
  capacity="10G"
fi

layout="$(garage layout show 2>/dev/null || true)"
if echo "$layout" | grep -q 'version: 0' || echo "$layout" | grep -q 'No nodes'; then
  node_id="$(garage node id | tr -d '\r' | grep -Eo '[a-f0-9]{64}' | head -n 1 || true)"
  if [ -z "$node_id" ]; then
    die "Could not determine Garage node id."
  fi

  log "Configuring Garage layout (capacity=${capacity})..."
  garage layout assign "$node_id" -z dc1 -c "$capacity" >/dev/null
  garage layout apply --version 1 >/dev/null
else
  log "Garage layout already configured."
fi

bucket="${S3_BUCKET_NAME:-odk-central}"
key_name="odk-central-key"

if garage bucket list 2>/dev/null | grep -q "\\b${bucket}\\b"; then
  log "Bucket '${bucket}' already exists."
else
  log "Creating bucket '${bucket}'..."
  garage bucket create "$bucket" >/dev/null
fi

access_key="${S3_ACCESS_KEY:-}"
secret_key="${S3_SECRET_KEY:-}"

if [ -n "$access_key" ] && [ -n "$secret_key" ]; then
  if garage key info "$access_key" >/dev/null 2>&1; then
    log "Reusing existing S3 key from .env (${access_key})."
  else
    log "Key from .env not found in Garage; creating a new one."
    access_key=""
    secret_key=""
  fi
fi

if [ -z "$access_key" ] || [ -z "$secret_key" ]; then
  log "Creating S3 key '${key_name}'..."
  out="$(garage key create "$key_name" 2>&1)"
  access_key="$(echo "$out" | grep -E '^Key ID:' | head -n 1 | sed -E 's/^Key ID:[[:space:]]*//')"
  secret_key="$(echo "$out" | grep -E '^Secret key:' | head -n 1 | sed -E 's/^Secret key:[[:space:]]*//')"
  if [ -z "$access_key" ] || [ -z "$secret_key" ]; then
    echo >&2 "$out"
    die "Failed to parse key output from Garage."
  fi
fi

log "Granting key permissions..."
garage bucket allow "$bucket" --read --write --key "$access_key" >/dev/null || true

update_env_kv() {
  local key="$1"
  local value="$2"
  local tmp
  tmp="$(mktemp)"
  if grep -qE "^[# ]*${key}=" .env; then
    awk -v k="$key" -v v="$value" '
      BEGIN { done=0 }
      {
        if (!done && $0 ~ "^[# ]*" k "=") { print k "=" v; done=1; next }
        print
      }' .env > "$tmp"
  else
    cat .env > "$tmp"
    {
      echo ""
      echo "# OVERRIDES (generated by scripts/add-s3.sh)"
      echo "${key}=${value}"
    } >> "$tmp"
  fi
  mv "$tmp" .env
}

update_env_kv S3_BUCKET_NAME "$bucket"
update_env_kv S3_ACCESS_KEY "$access_key"
update_env_kv S3_SECRET_KEY "$secret_key"

log "Updated .env with S3 credentials."
log "Restart Central services:"
log "  docker compose -f docker-compose.yml -f docker-compose-garage.yml restart service nginx"
